[workspace]

members = [
    "certutils",
    "certgen",
    "io-copy",
    "tcp-server",
    "tcp-echo",
    "tcp-client",
    "tcp-fibonacci",
    "tls-server",
    "katey-el-es",
    "katey-client",
    "integration-test"
]
