[[program]]
name = "other-certgen"
exec = "certgen"
args =  ["tree", "other-root", "other-client"]
ready = { completed={} }

[[program]]
name = "certgen"
exec = "certgen"
args = ["tree", "root", "server", "client"]
ready = { completed={} }

[[program]]
name = "echo"
exec = "tcp-echo"
args = ["--debug", "--port", "4000"]
ready = { port=4000 }

[[program]]
name = "fibonacci"
exec = "tcp-fibonacci"
args = ["--debug", "--port", "4001", "--interval", "0.01"]
ready = { port=4001 }

[[program]]
name = "katey-echo"
exec = "katey-el-es"
args = ["--debug", "--cert", "server-cert.pem", "--key", "server-key.pem", "5000", "localhost:4000"]
ready = { port=5000 }
depends = ["certgen", "echo"]

[[program]]
name = "katey-fibonacci"
exec = "katey-el-es"
args = ["--debug", "--cert", "server-cert.pem", "--key", "server-key.pem", "5001", "localhost:4001", "--authenticate", "root-cert.pem"]
ready = { port=5001 }
depends = ["certgen", "fibonacci"]

[[program]]
name = "smoke-test"
exec = "./run.sh"
ready = { completed={} }
depends = ["other-certgen", "certgen", "echo", "fibonacci", "katey-echo", "katey-fibonacci"]
